### ISSUE TITLE
I am not able to change the position of watermark

### ISSUE THREAD

**Issue by raut-santosh** [admondtamang/pdf-watermark#4]

**Comment by admondtamang** [comment]
Use imageOption to change the position of image. change x and y position to adjust position.
Below is sample code for change position.
` await PDFWatermark({
    pdf_path: "somefile.pdf",
    image_path: "./logo.png",
    text: "Tech sdlkf",
    textOption: {
      size: 240,
    },
    imageOption: {
      x: 300,
      y: 200,
    },
    output_dir: "./output.pdf", // remove to override file
  });`
